#!/usr/bin/env python

# script made to change model indicator in header 
# Run 'change_MOD input_file output_file '1'  ' for example
import sys

file=sys.argv[1]
file_ou=sys.argv[2]
model_char=sys.argv[3]

if type(model_char)!=str:
	if len(model_char)>1:
		print '2nd argument should be a string of one character'
		sys.exit()


print 'Be sure is has a nordic file format'


f1=open(file,'r')
lines=f1.readlines()
f1.close()

fo=open(file_ou,'w')

for line in lines:
	if len(line)>81:
		print 'Line exceeds 80 character, check input file'
	if line[-2]!='1':
		fo.write('%s' %line)
	else:
		header=list(line)
		header[20]=model_char
		new_header=''.join(header)	
		fo.write('%s' %new_header)
	
fo.close()
		


	