#!/usr/bin/env python

''' Made to read cnv file and convert it to xyz'''


import sys


file=sys.argv[1]
fileout=sys.argv[2]

fic=open(file,'r')
foc=open(fileout,'w')

for line in fic.readlines():
     if line[0]==' ':
     	rh=line[35]
     	nh=line[25]
     	if nh=='N':
     		lat=float(line[18:25])
     	else:
     		lat=-float(line[18:25])
     	if rh=='E':
     		lon=float(line[27:35])
     	else:
     		lon=-float(line[27:35])
     	
     	depth=float(line[37:43])
     	foc.write('%9.3f %9.3f %7.2f\n'%(lon,lat,depth))
	 
	 
fic.close()
foc.close()