#!/bin/bash
##

case $# in
0) 
	echo -n 'Start year: '
	read startyear
	echo -n 'Start month (MM): '
	read startmonth
	echo -n 'Start day (DD): '
	read startday
	echo -n 'End year:   '
	read endyear
	echo -n 'End month (MM):   '
	read endmonth
	echo -n 'End day (DD):   '
	read endday
	
	echo "Choose map range:"
	select maprange in Vanuatu SouthVanuatu NorthVanuatu  Shefa;
	do
		break
	done
	;;
7) 
	startyear=$1
	startmonth=$2
	startday=$3
	endyear=$4
	endmonth=$5
	endday=$6
	maprange=$7
	;;
*) 
	echo " $# arguments"
	echo "Usage: getUSGSdata (interactive)"
	echo "Usage: -or- getUSGSdata startyear startmonth startday endyear endmonth endday maprange"
	echo "Returns USGS epicenters in csv format for a given zone and date range"
	exit;;
esac
	
case $maprange in
	Shefa )
		latmin="-18.75"
		latmax="-16.50"
		lonmin="167.0"
		lonmax="169.5"
		 ;;
	SouthVanuatu )
		latmin="-20.5"
		latmax="-15.0"
		lonmin="165.0"
		lonmax="171.5"
		 ;;
	NorthVanuatu )
		latmin="-17"
		latmax="-12.5"
		lonmin="165.5"
		lonmax="169"
		 ;;
	Vanuatu )
		latmin="-22"
		latmax="-10"
		lonmin="162"
		lonmax="172"
		 ;;
	* ) echo -n "Invalid map range: $maprange"; exit 1;;
esac

curl "http://neic.usgs.gov/cgi-bin/epic/epic.cgi?SEARCHMETHOD=2&FILEFORMAT=6&SEARCHRANGE=HH&SLAT2=${latmax}&SLAT1=${latmin}&SLON1=${lonmin}&SLON2=${lonmax}&SYEAR=${startyear}&SMONTH=${startmonth}&SDAY=${startday}&EYEAR=${endyear}&EMONTH=${endmonth}&EDAY=${endday}&LMAG=&UMAG=&NDEP1=&NDEP2=&IO1=&IO2=&CLAT=0.0&CLON=0.0&CRAD=0.0&SUBMIT=Submit+Search" | sed -n '/Year,Month,Day,Time/,/\/pre/p' | sed -n '/[0-9][0-9][0-9][0-9],[0-9][0-9],[0-9][0-9],/p' > USGSdata.csv

