#!/usr/bin/env python

import sys
import os
from datetime import datetime, date, time

''' Program made to convet norfile into lon/lat/depth/mag/datenum table (Matlabdatenum)'''

#file='/Users/baillard/_Moi/Programmation/Matlab/Santo_2000/Data/santo2000_0.out'

if len(sys.argv)==1:
	print 'Put one nordic file as argumen'
	sys.exit()
elif len(sys.argv)>2:
	print 'Put only one file as argument'
	sys.exit()

file=sys.argv[1]

os.system('nor2xyz %s > temp.xyz'%file)

fic=open('temp.xyz','r')
lines=fic.readlines()
fic.close()

for line in lines:

	A=line.split()
	lon,lat,depth=float(A[0]),float(A[1]),float(A[2])
	time=A[3]
	year=float(time[0:4])
	month=float(time[5:7])
	day=float(time[8:10])
	hour=float(time[11:13])
	min=float(time[14:16])
	sec=float(time[17:21])
	mag=float(A[4])

	d = date(int(year), int(month), int(day))
	datenum=d.toordinal()+hour/24.0+min/(24.0*60)+sec/(24.0*60*60)+366  ## to have matlab datenum
	
	print '%9.3f %9.3f %8.2f %4.1f %16.7f' %(lon,lat,depth,mag,datenum)
	
os.system('rm -f temp.xyz')


