#!/bin/bash

export LC_NUMERIC=POSIX
filename=$1

if [ -f scratch3.txt ]
then
    rm -f scratch3.txt
fi

# Convert to xyz format
nor2xyz $filename | awk '{print substr($4,0,19)}' > scratch1.txt
nor2xyz $filename > scratch2.txt

# Get abssolute time in second
a=0
while read line
do a=$(($a+1));
#echo $line;
tic=$(date -j -f "%Y-%m-%dT%H:%M:%S" $line +%s)
fat=$(echo "scale=4; $tic/86400" | bc)
echo $fat >> scratch3.txt
done < scratch1.txt

# Replace column in file
paste -d" " scratch2.txt scratch3.txt | awk '{ print $1,$2,$3, $11 ,$5,$6,$7,$8,$9, $10}'
#$(echo "scale=3;4.5/100" | bc )
# Remove unwanted files
rm -f scratch1.txt
rm -f scratch2.txt
rm -f scratch3.txt

